apiVersion: v1
kind: Secret
metadata:
  name: scaleops-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://registry.scaleops.com/charts/
  username: scaleops
  password: ***