apiVersion: v1
kind: Secret
metadata:
  name: repo-6522610
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
data:
  name: argo-lab
  project: default
  sshPrivateKey: >-
    ***
  type: git
  url: <REPO_NAME>
type: Opaque
