apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: java-flux
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tomcat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tomcat
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8088'
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -javaagent:/data/jmx_prometheus_javaagent-1.1.0.jar=8088:/data/prometheus-jmx-config.yaml -Xmx128m -Xms128m
        - name: JAVA_AGENT_PORT
          value: "8088"
        image: stevenfeltner/tomcat-jvm:latest
        imagePullPolicy: IfNotPresent
        name: tomcat
        resources:
          requests:
            cpu: 400m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30