apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: annotations
  namespace: argocd
spec: 
  project: default
  source:
    path: annotations
    repoURL: git@github.com:anthony-scaleops/argo-lab.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true